show databases;
create schema cars;
SELECT * FROM cars.car_dekho;
USE cars;

 --   READING DATA
 SELECT * FROM car_dekho;
 
-- TOTAL CARS - TO GET A COUNT OF TOTAL RECORDS-- 
SELECT COUNT(*) FROM car_dekho;

-- NUMBER OF CARS AVAILABLE IN 2023
SELECT  COUNT(*) FROM car_dekho WHERE year=2023;

-- NUMBER OF CARS AVAILABLE IN 2020,2021,2022
SELECT COUNT(*) FROM car_dekho WHERE year IN (2020,2022);
SELECT count(*) FROM car_dekho WHERE year IN (2020,2021,2022) GROUP BY year;
 
--  --PRINT TOTAL OF ALL CARS BY YEAR--  
SELECT year,count(*) FROM car_dekho   GROUP BY year;

-- NUMBER OF CARS IN THE YEAR 2020
SELECT count(*) FROM car_dekho WHERE year=2020 AND fuel="Diesel";

-- NUMBER OF PETROL CARS IN THE YEAR 2020
SELECT COUNT(*) FROM car_dekho WHERE year=2020 and fuel="petrol";  #51

-- PRINT ALL THE FUEL CARS(PETROL,DIESEL,CNG)  BY ALL YEAR
SELECT COUNT(*) FROM car_dekho WHERE fuel="petrol" GROUP BY year;
SELECT COUNT(*) FROM car_dekho WHERE fuel="diesel" GROUP BY year;
SELECT COUNT(*) FROM car_dekho WHERE fuel="CNG" GROUP BY year;

-- WHICH IS THE YEAR WHICH HAS HAD MORE THAN 100 CARS?
SELECT year,COUNT(*) FROM car_dekho GROUP BY year HAVING COUNT(*)>100;

-- PRINT CAR DETAILS OF ALL CARS BETWEEN YEAR 2015 AND 2023
SELECT * FROM car_dekho WHERE year IN(2015,2023);

-- PRINT CAR COUNT OF ALL CARS BETWEEN YEAR 2015 AND 2023
SELECT COUNT(*) FROM car_dekho WHERE year IN (2015,2023);  